### ISSUE TITLE
Move clocks to Context

### ISSUE THREAD

**Issue by pefribeiro** [robo-star/circus.robocalc.robochart.parent#3]
Noting that the attribute `clocks` should be moved to the `Context` element, so as to allow clocks declared in an interface, to be required by a _software_ operation in RoboChart and RoboSim.

@alvarohm does this mean that each concrete instance of such an ECore model needs to be updated manually, or is this automatically accounted for by ECore? If it isn't, how easy is it to deploy an way to update existing RoboChart projects?

This also requires the definition of additional validation rules to prevent clocks from being misused in other `Context`s that is not a _software_ operation.

**Comment by pefribeiro** [comment]
@alvarohm do you think it would be possible to do this soon?

**Comment by alvarohm** [comment]
Hi Pedro,

I had started it but not yet finished. I've added it to BasicContext (which is the parent of Interface).

In the grammar, I had added clocks to interfaces, but I'm not sure if they should also be in controllers and robotic platforms. Can you clarify it, please?

**Comment by pefribeiro** [comment]
> I had started it but not yet finished. I've added it to BasicContext (which is the parent of Interface).

Thanks for the quick reply.

> In the grammar, I had added clocks to interfaces, but I'm not sure if they should also be in controllers and robotic platforms. Can you clarify it, please?

Other than state machines, they should only be in interfaces. Not in any controllers or robotic platforms.

**Comment by alvarohm** [comment]
ok. since the metamodel will allow those cases, I'll add validation rules to check that there are not clocks in controllers or platforms. I'll let you know when I'm done with this.

**Comment by pefribeiro** [comment]
> ok. since the metamodel will allow those cases, I'll add validation rules to check that there are not clocks in controllers or platforms. I'll let you know when I'm done with this.

Understood. Thanks.

We will also need validation to ensure that a state machine declares all clocks that are 'required' by operations required by that state machine. I suppose that similarly to variable, a state machine will be able to 'use' an interface with clocks (like with variables, understood as if declared in the state machine), but an operation will need to require. Is that correct?

I'll also need to update the semantics to deal with the clocks in interfaces, but that's after the metamodel is in place.

**Comment by alvarohm** [comment]
I have updated the metamodel, textual and graphical plugins.

> We will also need validation to ensure that a state machine declares all clocks that are 'required' by operations required by that state machine. I suppose that similarly to variable, a state machine will be able to 'use' an interface with clocks (like with variables, understood as if declared in the state machine), but an operation will need to require. Is that correct?

I believe that should be the case.

I need to add more rules, I think they are:

1) provided interfaces cannot have clocks (only used and required interfaces)
2) platforms cannot use interfaces containing clocks
3) controllers cannot use or require interfaces containing clocks
4) state machines cannot require interfaces containing clocks (only use them)
5*) operations can requires or use interfaces containing clocks

* the last is not really a condition, just a clarification

Do you agree with these conditions?

> 
> I'll also need to update the semantics to deal with the clocks in interfaces, but that's after the metamodel is in place.

that's done

**Comment by pefribeiro** [comment]
> I have updated the metamodel, textual and graphical plugins.

Thanks. Fantastic. Does Madiel need to reflect this in the RoboSim plugins? I suppose so, and, perhaps need to recompile all those as well?

> Do you agree with these conditions?

Yes, in agreement with all.

> > I'll also need to update the semantics to deal with the clocks in interfaces, but that's after the metamodel is in place.
> 
> that's done

Oh, right! Fantastic.

**Comment by alvarohm** [comment]
After a quick look at the robosim plugins, I seems like a recompilation should suffice. The metamodel of robosim does not touch on interfaces and extends state machine def, so it should be fine.

The grammar also does not seem to redefine interfaces, and state machine defs already have clocks there.

I believe the well-formedness conditions are also inherited.

**Comment by alvarohm** [comment]
Updated in commits:

9aab6ceb22d15f15ffbdd7a7526b8d4a63e550e8
3ada651c535564c14a1bd54cce847ef1d68028df
6f6f40a01461e50529d79dc3e38fd09f89b1d6f2
a7d1ba50d404d70746817e6fd2fabd38bc69bc9d
